---
map_name: "Canals of Chlorine Kingdoms"
author: "Cokemonkey11"
repo_uri: https://github.com/Cokemonkey11/canals-of-chlorine-kingdoms/
contributing: This map is fully open source, but I am not currently accepting pull requests.
introduction: |+
  Canals of Chlorine Kingdoms is a MOBA designed from the ground up to reward the most skilled team, and to be played in 20-30 minutes -- even in a fair matchup.

  Join the battle-net community of playtesters!

  https://blizzard.com/invite/wWMvEyMCZnV
screenshots:
  - caption: 11 heroes to choose from
    uri: https://rimgo.pussthecat.org/wKZhaR5.png
  - caption: Many classic AoS elements are present (creep blocking)
    uri: https://rimgo.pussthecat.org/duFVdmv.png
  - caption: Many classic AoS elements are present (last-hitting)
    uri: https://rimgo.pussthecat.org/Kl9AzQV.png
  - caption: Many classic AoS elements are present (denying)
    uri: https://rimgo.pussthecat.org/Wc4xw2l.png
  - caption: Tower shots can be dodged!
    uri: https://rimgo.pussthecat.org/DlQWWfy.png
  - caption: Many hero abilities can be dodged!
    uri: https://rimgo.pussthecat.org/YuH7Nmr.png
  - caption: Get closer to the enemy to improve your chances of landing skill-shots
    uri: https://rimgo.pussthecat.org/JzXoJqd.png
  - caption: All heroes can flash, as well as channel to recall back to base
    uri: https://rimgo.pussthecat.org/192Wqfo.png
  - caption: Ganking provides a significant gold advantage with an extra 5 gold awarded to all assisting players upon kill
    uri: https://rimgo.pussthecat.org/kqENLY1.png
  - caption: Rather than a neutral jungle, Chlorine features a power-leveling chamber that turns on at 9m0s
    uri: https://rimgo.pussthecat.org/jqQPQ0q.png
  - caption: The Space Cadet features abilities that augment its basic attack
    uri: https://rimgo.pussthecat.org/9uI8pXH.png
  - caption: In-depth stats are collected during the game (damage)
    uri: https://rimgo.pussthecat.org/j11IiT5.png
  - caption: In-depth stats are collected during the game (gold)
    uri: https://rimgo.pussthecat.org/4mRDJ7A.png
  - caption: In-depth stats are collected during the game (hero damage)
    uri: https://rimgo.pussthecat.org/DJSXqdQ.png
icon_table:
  title: "Heroes"
  contents:
    - caption: Space Cadet, Ranged carry, can cast divine shield. Abilities mostly augment basic attack.
      uri: https://rimgo.pussthecat.org/QFkaijW.png
    - caption: Night Howler, Ranged carry, can instagib low-health targets.
      uri: https://rimgo.pussthecat.org/JccoDDT.png
    - caption: Headbanger, Ranged carry, can throw long-ranged spears.
      uri: https://rimgo.pussthecat.org/ZbQGv7t.png
    - caption: Goblin Bloodbomber, Ranged carry, can juggle blood bombs to sustain health.
      uri: https://rimgo.pussthecat.org/6g0AWbZ.png

    - caption: Steel Elemental, Bursty tank, can dash and multi-stomp.
      uri: https://rimgo.pussthecat.org/weA2TUS.png
    - caption: Tauren Gladiator, Bruiser tank, can leap and stun starting at level 1.
      uri: https://rimgo.pussthecat.org/hrQloIF.png
    - caption: Mongo, Supportive tank, can hook enemies.
      uri: https://rimgo.pussthecat.org/MSnxTLB.png

    - caption: Sorcerer, Scaling caster, can multi-cast with abilities that deal scaling damage.
      uri: https://rimgo.pussthecat.org/iY56lGe.png
    - caption: Molotov Cockatiel, Agile caster, can dash and retreat with some setup.
      uri: https://rimgo.pussthecat.org/iqUZP6v.png
    - caption: Void Annihilator, Supportive caster, can teleport and lock down enemies with a skillshot.
      uri: https://rimgo.pussthecat.org/tsrykUH.png
    - caption: Centaur Worldbender, Disurptive caster, can zone, silence, and levitate enemies.
      uri: https://rimgo.pussthecat.org/5QHXx2M.png

changelog:
  - version: 0.4.3
    date: 24 May 2024
    changes:
      - Fixed a bug where casting Dunk on self would result in being permanently stuck
      - Improved the predictability of bloobomb catching
      - Water Shield can now be cast on invulnerable allies
      - Fixed two more instances of an unintentionally globally-played sound effects
      - Improved the visual clarity of Collector mana collection
      - Improved the visual clarity of Rhythm of the Blood Sigil
      - Addressed a nitpick - after selecting your hero, the spawned hero becomes selected automatically
  - version: 0.4.2
    date: 23 May 2024
    changes:
      - Improved the predictability of bloobomb catching
      - Binded bloodbombers can no longer dash using rhythm of the blood sigil
      - Fixed bugs where Rhythm of the Blood Sigil and Flash didn't respect Telekenesis
      - Fixed a bug where some order IDs would unpredictably have a collision depending on the map version
      - Fixed another instance of an unintentionally "global" sound effect
      - Improved the visual clarity of Collector mana collection
      - Improved the visual clarity of Telekenesis floating rocks
  - version: 0.4.1
    date: 14 May 2024
    changes:
      - Map released on hiveworkshop!
      - Minor balancing changes
  - version: 0.4.0
    date: 14 May 2024
    changes:
      - New hero, Goblin Bloodbomber
      - Minor tweaks to the Centaur Worldbender
      - Increased the camera shake of Tauren Gladiator Dunk
      - Fixed some unintentionally global sound effects
      - Improved the description of Tauren Gladiator's ult, Brain Drill
      - Fixed a bug that enabled Ice Blast to hit towers and other structures
  - version: 0.3.0
    date: 8 May 2024
    changes:
      - New hero added - Centaur Worldbender
      - Improved the hero selection experience
      - Melee heroes are no longer selectable
  - version: 0.2.0
    date: 7 May 2024
    changes:
      - Assists and assist gold added
      - Added quests menu with game design information and tips
      - Fixed an issue where flash wouldn't disjoint space cadet stun
      - Fixed a stacktrace when using black binding
      - Adjusted void annihilator ult cooldown and adjusted tauren gladiator seppuku scaling
      - Adjusted black binding collision size
      - Wallbang can no longer target allied units
      - Changed some assets for clarity
      - Revive now respawns with 100% mana
      - Stats are now dumped to disk at the end of a game; it is possible to generate graphs of game stats
  - version: 0.1.2
    date: 1 May 2024
    changes:
      - Minor balancing changes
  - version: 0.1.0
    date: 30 Apr 2024
    changes:
      - Added a new hero -- Headbanger, carry
      - Fixed a number of known bug cases where sounds were played "globally" when they should be attached to a unit or point
  - version: 0.0.11
    date: 23 Apr 2024
    changes:
      - Replaced blood mage with arch mage to prevent abuse with phoenix
      - Replaced lich with sea witch to avoid the same issue with hover units that cockatiel had
      - Heroes are now invulnerable for a few seconds when respawning
      - Added warning messages when a non-shade tries to pick a hero
  - version: 0.0.10
    date: 23 Apr 2024
    changes:
      - Fixed a critical bug where knockback on a cockataiel would send you to the edge of the map
      - Reduced night howler attack range and attack buff duration
      - Swapped alchemist for pit lord
      - Made flash and recall "permanent" abilities to morphing heroes (avatar, etc)
      - Immolation can now be cast against invulnerable allied heroes
  - version: 0.0.8
    date: 23 Apr 2024
    changes:
      - Add new heroes - Molotov Cockatiel and Tauren Gladiator
      - New abilities for all existing heroes, completing their 4-ability rosters.
      - Exp sharing is now calculated when multiple allied heroes observe exp
      - Sharing items is no longer allowed
      - Leavers heroes are now removed from play rather than at the base
      - Added kill notifications when heroes are slain
      - Kills are now awarded to the last damaging hero rather than the kingdom, in the case that the kingdom takes the last-hit
      - Game timer added
      - Revive timers added
      - Balance changes (Raid Boss now grants +2500 HP, down from 5000; In-base healing increased to 4%, up from 2%; Castle HP doubled)
      - Bug fixes (Space Cadet's charged blast can no longer stun invulnerable units, Flash now disjoints Space Cadet's charged blast)
  - version: 0.0.4
    date: 17 Apr 2024
    changes:
      - Add purchaseable base items
      - Add Void Annihilator ability - "Regenerator"
      - Add Steel Elemental ability - "Clap"
      - Add Night Howler ability - "Finger"
      - Add Mongo ability - "Amnesia"
      - Add Sorcerer ability - "Ice Blast"
      - Fix Exasperation item
      - Add Space Cadet ability - "Charged Blast"
      - Add Space Cadet ability - "Volley"
      - All heroes can now Flash
      - Tranche of balance changes and nits
  - version: 0.0.3
    date: Unknown
    changes:
      - Add Void Annihilator, Steel Elemental, Night Howler, Mongo, Sorcerer, and Space Cadet
      - Add expensive items
  - version: 0.0.0
    date: 11 Mar 2024
    changes:
      - Initial playtest using melee heroes.
credits:
  - peq
  - Frotty
  - Matro
  - lep
  - Petr
  - Overkane
  - DiscoOrc
  - Jaccouille
  - Footman16
  - Krakena
  - I1337h4x0RI
  - WaterKnight
  - looking_for_help
  - Blizzard Entertainment
  - hiveworkshop.com
  - Dionesiist
  - SGT Phill
  - Black_Stan
  - The D3ath
  - Deolrin
  - Norinrad
  - CRAZYRUSSIAN
  - Marcos DAB
  - KelThuzad
  - Remixer
